global:
  scrape_interval:     5s
  evaluation_interval: 5s

  external_labels:
      monitor: 'prometheus-grafana-exporter'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server-core'
    metrics_path: /metrics  
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'server-pici'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.0.10.67:9100']

  - job_name: 'server-quixada'
    metrics_path: /metrics
    static_configs:
      - targets: ['10.0.200.100:9100']

  - job_name: 'container-core'
    static_configs:
      - targets: ['cadvisor:8080']
      
  - job_name: 'container-pici'
    static_configs:
      - targets: ['10.0.10.67:8080']

  - job_name: 'container-quixada'
    static_configs:
      - targets: ['10.0.200.100:8080']

  - job_name: 'edge-nodes-pici'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    static_configs:
      - targets: ['10.0.20.15:19999']
        labels:
          group: 'jetson-xavier-nx-1'
      - targets: ['10.0.20.11:19999']
        labels:
          group: 'raspberrypi4-1'

